name: testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install python-dotenv

    - name: Install MySQL Client
      run: sudo apt-get install mysql-client
    
    - name: Set up environment variables
      run: |
        echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
        echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" >> $GITHUB_ENV

    - name: Debug MySQL Connection
      run: |
        mysql --version
        service mysql status
        cat /var/log/mysql/error.log  # Adjust the path to your MySQL error log


    - name: Create database
      run: |
        mysql -u${{ secrets.DATABASE_USER }} -p${{ secrets.DATABASE_PASS }} -e "CREATE DATABASE IF NOT EXISTS ${{ secrets.DATABASE_NAME }};"

    - name: Run tests
      run: python manage.py test