name: testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASS }}
          MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
        ports: ['3306:3306']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --user -r requirements.txt
        pip install python-dotenv

    - name: Install mysqlclient
      run: |
        sudo apt-get install libmysqlclient-dev
        pip install mysqlclient
    
    - name: Set up environment variables
      run: |
        echo "SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
        echo "DATABASE_NAME=${{ secrets.DATABASE_NAME }}" >> $GITHUB_ENV
        echo "DATABASE_USER=${{ secrets.DATABASE_USER }}" >> $GITHUB_ENV
        echo "DATABASE_PASS=${{ secrets.DATABASE_PASS }}" >> $GITHUB_ENV

    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: ${{ secrets.DATABASE_NAME }}
        DBUSER: ${{ secrets.DATABASE_USER }}
        DBPASSWORD: ${{ secrets.DATABASE_PASS }}

    - name: Run tests
      run: python manage.py test